syntax match Isoleucine "I"
syntax match Leucine "L"
syntax match Valine "V"
syntax match Phenylalanine "F"
syntax match Methionine "M"
syntax match Cysteine "C"
syntax match Alanine "A"
syntax match Glycine "G"
syntax match Proline "P"
syntax match Threonine "T"
syntax match Serine "S"
syntax match Tyrosine "Y"
syntax match Tryptophan "W"
syntax match Glutamine "Q"
syntax match Asparagine "N"
syntax match Histidine "H"
syntax match GlutamicAcid "E"
syntax match AsparticAcid "D"
syntax match Lysine "K"
syntax match Arginine "R"

highlight Isoleucine ctermfg=0 ctermbg=216
highlight Leucine ctermfg=0 ctermbg=206
highlight Valine ctermfg=0 ctermbg=226
highlight Phenylalanine ctermfg=0 ctermbg=126
highlight Methionine ctermfg=0 ctermbg=136
highlight Cysteine ctermfg=0 ctermbg=146
highlight Alanine ctermfg=0 ctermbg=156
highlight Glycine ctermfg=0 ctermbg=176
highlight Proline ctermfg=0 ctermbg=186
highlight Threonine ctermfg=0 ctermbg=196
highlight Serine ctermfg=0 ctermbg=26
highlight Tyrosine ctermfg=0 ctermbg=36
highlight Tryptophan ctermfg=0 ctermbg=46
highlight Glutamine ctermfg=0 ctermbg=56
highlight Asparagine ctermfg=0 ctermbg=66
highlight Histidine ctermfg=0 ctermbg=76
highlight GlutamicAcid ctermfg=0 ctermbg=86
highlight AsparticAcid ctermfg=0 ctermbg=96
highlight Lysine ctermfg=0 ctermbg=27
highlight Arginine ctermfg=0 ctermbg=190
