#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
# move mouse to center of focused window
yabai -m config mouse_follows_focus          off
# === focus_follows_mouse ===
# off
# autofocus: window gets focused, but not raise
# autoraise: window gets raised as if it was clicked on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_placement      inset
yabai -m config window_border_width          4
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
# yabai -m config mouse_modifier               fn
yabai -m config mouse_modifier               cmd
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
# yabai -m config layout                       bsp
yabai -m config layout                       float
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   10

# rules
yabai -m rule --add label=system-preferences app="System Preferences" manage=off
yabai -m rule --add label=mail-preferences app=Mail title=General manage=off

# yabai -m rule --add label=all_float \
#     app=".*"
#     manage=off

# yabai -m signal --add label=all_window_created event=window_created app=".*" action='/Users/jmazz/bin/yabai/all_window_created.sh $YABAI_WINDOW_ID'
# event=application_launched $YABAI_PROCESS_ID
# event=window_created $YABAI_WINDOW_ID

echo "yabai configuration loaded.."
