#!/bin/sh

feh --bg-scale ~/Pictures/Wallpapers/neon-demon.jpg

compton --no-fading-openclose -b

sxhkd &
libinput-gestures-setup start &
$HOME/.config/polybar/launch.sh

# ~/.config/bspwm/panel &
# bspc subscribe report > "$PANEL_FIFO" &

# bspc config top_padding $PANEL_HEIGHT

bspc monitor -d I II III

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Nautilus state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
