#!/bin/sh

feh --bg-scale ~/Pictures/Wallpapers/neon-demon.jpg
# feh --bg-scale ~/Pictures/Wallpapers/WelcometoRoboCity16_4K.jpg

compton -c --no-fading-openclose --shadow-exclude-reg 2720x52+0+0 -b
# --shadow-exclude '!focused'

# plank
/usr/lib/bamf/bamfdaemon-dbus-runner &
bspc rule -a Plank layer=above manage=off border=off

# xfsettingsd &
xfce4-panel &
# xfdesktop &


# sxhkd &
sxhkd -m -1 &
libinput-gestures-setup start &
$HOME/.config/polybar/launch.sh

# ~/.config/bspwm/panel &
# bspc subscribe report > "$PANEL_FIFO" &

# bspc config top_padding $PANEL_HEIGHT
bspc config initial_polarity second_child
bspc monitor -d I II III

bspc config border_width         4
# bspc config focused_border_color #A15FA9
# bspc config focused_border_color #0C99A2
bspc config focused_border_color \#dfdfdf
bspc config window_gap          12

# bspc config bottom_padding 50
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus button1
bspc config focus_follows_pointer true                                                               
bspc config swallow_first_click false

# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
# bspc rule -a Nautilus state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


plank &

# start subscribers
~/.config/bspwm/subscribe/node_add.sh &
~/.config/bspwm/subscribe/desktop.sh &

# init
~/.config/bspwm/subscribe/scripts/pager-rows.sh &

# setting again...
bspc config focus_follows_pointer true
