#!/bin/bash

echo "Init submodules"
source <(curl -fsSL 'https://github.com/TheLocehiliosan/yadm/raw/master/bootstrap') && yadm submodule update --init --recursive

if command -v nvim >/dev/null 2>&1; then
    echo "Installing vim-plug plugins for Neovim"
    nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

if [ ! -d ~/.tmux/plugins/tpm ]; then
    echo "Cloning tpm"
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    echo "Installing tmux plugins"
    ~/.tmux/plugins/tpm/bin/install_plugins
fi
